lightfulhelps/ray

dist/js/components/Dropdown/Dropdown.js
dist/js/components/DropdownItem/DropdownItem.js
dist/js/components/DropdownMenu/DropdownMenu.js
dist/js/components/Icon/Icon.js
src/js/components/Button/__snapshots__/Button.spec.js.snap
src/js/components/Dropdown/Dropdown.js
src/js/components/DropdownItem/DropdownItem.js
src/js/components/DropdownMenu/DropdownMenu.js
src/js/components/Icon/Icon.js
src/js/components/PostCard/__snapshots__/PostCard.spec.js.snap
src/js/stories/Dropdown.stories.js

iconColor in DropdownItem

---

package.json
src/js/components/Dropdown/__snapshots__/Dropdown.spec.js.snap
yarn.lock

Greenkeeper/babel eslint 10.0.1

---

dist/js/components/SearchSuggest/SearchSuggest.js
src/js/components/SearchSuggest/SearchSuggest.js
src/js/components/SearchSuggest/SearchSuggest.spec.js

Add an `exclude` prop to exclude characters from search matching with a string or RegExp.

Allow string or regex option to exclude characters from search

---

dist/css/ray.css
dist/js/components/PostCardGhost/PostCardGhost.js
dist/js/index.js
src/js/components/PostCardGhost/PostCardGhost.js
src/js/components/PostCardGhost/PostCardGhost.spec.js
src/js/components/PostCardGhost/__snapshots__/PostCardGhost.spec.js.snap
src/js/index.js
src/js/stories/PostCard.stories.js
src/scss/_custom.scss
src/scss/_variables.scss
src/scss/custom/_ghost.scss
src/scss/utilities/_borders.scss

Add a "ghost" post card component.

Ghost post card

---

dist/css/ray.css
dist/js/components/FormSelect/ClearIndicator.js
dist/js/components/FormSelect/DropdownIndicator.js
src/js/components/FormSelect/ClearIndicator.js
src/js/components/FormSelect/DropdownIndicator.js
src/js/stories/Forms.stories.js
src/scss/_forms.scss
src/scss/_variables.scss
src/scss/custom/_form-select.scss
yarn.lock

Input style

---

.stylelintrc.js
dist/css/ray.css
dist/js/components/Table/Table.js
dist/js/index.js
dist/js/stories/utils/sizes.js
src/js/components/Table/Table.js
src/js/components/Table/Table.spec.js
src/js/components/Table/__snapshots__/Table.spec.js.snap
src/js/index.js
src/js/stories/Button.stories.js
src/js/stories/Forms.stories.js
src/js/stories/Table.stories.js
src/js/stories/utils/sizes.js
src/scss/_tables.scss
src/scss/_variables.scss
src/scss/ray.scss

Table components and styling

---

package.json
yarn.lock

Greenkeeper/date fns 1.30.1

---

dist/js/components/PostCard/PostCard.js
src/js/components/PostCard/PostCard.js
src/js/components/PostCard/PostCard.spec.js
src/js/components/PostCard/__snapshots__/PostCard.spec.js.snap

Add year to postcard date

---

dist/css/ray.css
index.html
src/scss/_pagination.scss
src/scss/ray.scss

For the backoffice I would like to use the standard bootstrap pagination

Enable pagination classes

---

dist/js/components/PostCard/PostCard.js
dist/js/components/URLMetaPreview/URLMetaPreview.js
package.json
src/js/components/PostCard/PostCard.js
src/js/components/PostCard/PostCard.spec.js
src/js/components/PostCard/__snapshots__/PostCard.spec.js.snap
src/js/components/URLMetaPreview/URLMetaPreview.js
src/js/components/URLMetaPreview/__snapshots__/URLMetaPreview.spec.js.snap
yarn.lock

Switch to react-lines-ellipsis

Switch to react-lines-ellipsis

---

src/scss/utilities/_sizing.scss

This is for doing nice text truncation.
Following the pattern of https://github.com/twbs/bootstrap/blob/769c8d824600fbf521e3976cc4a3c6152ed4e8ce/scss/utilities/_sizing.scss

Add min-width utility class

---

dist/css/ray.css
dist/js/components/NavLink/NavLink.js
src/js/components/NavLink/NavLink.js
src/js/components/NavLink/NavLink.spec.js
src/js/components/NavLink/__snapshots__/NavLink.spec.js.snap
src/js/stories/Nav.stories.js
src/scss/_nav.scss

The changes add theming to the nav-link component. A new props theme is available. They are proposed to resolve this issue https://lightful.atlassian.net/browse/PLATFORM-685

Nav Theming

---

dist/css/ray.css
src/scss/_forms.scss

Reduce the checkbox size and prevent them getting squashed if the label is long.

Reduce checkbox size

---

dist/css/ray.css
dist/js/components/CampaignCard/CampaignCard.js
dist/js/index.js
src/js/components/CampaignCard/CampaignCard.js
src/js/components/CampaignCard/CampaignCard.spec.js
src/js/components/CampaignCard/__snapshots__/CampaignCard.spec.js.snap
src/js/index.js
src/js/stories/CampaignCard.stories.js
src/scss/_custom.scss
src/scss/custom/_campaign-card.scss

CampaignCard component

---

dist/js/components/CampaignTemplateCard/CampaignTemplateCard.js
dist/js/index.js
src/js/components/CampaignTemplateCard/CampaignTemplateCard.js
src/js/components/CampaignTemplateCard/CampaignTemplateCard.spec.js
src/js/components/CampaignTemplateCard/__snapshots__/CampaignTemplateCard.spec.js.snap
src/js/index.js
src/js/stories/CampaignTemplateCard.stories.js

https://lightful.atlassian.net/browse/PLATFORM-892
Created component and tests for the Campaign Template Card in storybuilder

PLATFORM-892 - Campaign Template Component

---

dist/css/ray.css
src/scss/_type.scss

Added important flag to text-underline class

---

dist/css/ray.css
dist/js/components/Progress/Progress.js
dist/js/index.js
src/js/components/CampaignTemplateCard/CampaignTemplateCard.spec.js
src/js/components/Progress/Progress.js
src/js/components/Progress/Progress.spec.js
src/js/components/Progress/__snapshots__/Progress.spec.js.snap
src/js/index.js
src/js/stories/Progress.stories.js
src/scss/ray.scss

- Enabling progress bar from Bootstrap
- Add Progress component

Progress component

---

dist/css/ray.css
dist/js/components/ToggleSwitch/ToggleSwitch.js
src/js/components/ToggleSwitch/ToggleSwitch.js
src/js/components/ToggleSwitch/ToggleSwitch.spec.js
src/js/stories/ToggleSwitch.stories.js
src/scss/_custom-forms.scss
src/scss/_variables.scss

Adding top and bottom position for toggle's label alignment for downgrading design. Updating stories and test.
- x ] If required, designers have signed off my changes

Adding top and bottom alignment for toggle's label

---

dist/css/ray.css
src/scss/_variables.scss

Increase text contrast in alert

Increase text contrast in alert

---

dist/js/components/Collapse/Collapse.js
src/js/components/Collapse/Collapse.js
src/js/components/Collapse/Collapse.spec.js
src/js/components/Collapse/__snapshots__/Collapse.spec.js.snap

Adding classes to collapse element for platform CSS override 

Add classes to collapse children

---

dist/css/ray.css
src/scss/_buttons.scss

Adding style to make buttons appear grey if disabled no matter the theme and overwrite the hover style
https://lightful.atlassian.net/browse/PLATFORM-418

PLATFORM-418 : Update disabled button style

---

dist/css/ray.css
src/scss/_variables.scss
src/scss/mixins/_buttons.scss

Just adding a box-shadow on focus to the button mixin. It corresponds to the style used by bootstrap.
https://lightful.atlassian.net/browse/PLATFORM-1197

PLATFORM-1197 : Adding boxshadow on button focus

---

dist/js/components/ResourceCard/ResourceCard.js
src/js/components/ResourceCard/ResourceCard.js
src/js/components/ResourceCard/ResourceCard.spec.js
src/js/stories/ResourceCard.stories.js

This is relating to this ticket: https://lightful.atlassian.net/browse/PLATFORM-1224
We require a background image on the resource cards in the storybuild in order to be inline with the design.

Added backgroundImage prop to resource card

---

dist/js/components/ResourceCard/ResourceCard.js
src/js/components/ResourceCard/ResourceCard.js
src/js/components/ResourceCard/ResourceCard.spec.js
src/js/stories/ResourceCard.stories.js

It seems that React gets confused if you call a prop `backgroundImage` when you pass it down. Renamed this so it works.

Fixed background image prop

---

package.json
src/js/components/InspirationPostCard/InspirationPostCard.spec.tsx
src/js/components/InspirationPostCard/InspirationPostCard.tsx
src/js/components/PostCard/PostCard.spec.tsx
src/js/components/PostCard/PostCard.tsx
yarn.lock

Update to date-fns 2.x.x and make it a peer dependency.

Update to date-fns 2

---

src/js/components/Progress/Progress.spec.tsx
src/js/components/Progress/Progress.tsx
src/js/components/Progress/__snapshots__/Progress.spec.tsx.snap
src/js/stories/Progress.stories.tsx

Add small, medium and large props for progress bar.
I'm aware that the select function in the .stories file isn't the tidiest. I tried assigning the function and/or the args to variables and it started doing exciting things. This is the only way it seemed to work.

Progress bar sizes

---

scripts/templates/component.tsx.hbs
src/js/components/MediaThumbnail/MediaThumbnail.spec.tsx
src/js/components/MediaThumbnail/MediaThumbnail.tsx
src/js/components/MediaThumbnail/__snapshots__/MediaThumbnail.spec.tsx.snap
src/js/index.ts
src/js/stories/InspirationPostCard.stories.tsx
src/js/stories/MediaThumbnail.stories.tsx
src/scss/_custom.scss
src/scss/_forms.scss
src/scss/custom/_media-thumbnail.scss

Adding new `MediaThumbnail` component.

MediaThumbnail component

---

src/js/components/Alert/Alert.spec.tsx
src/js/components/Alert/Alert.tsx
src/js/components/Alert/__snapshots__/Alert.spec.tsx.snap
src/js/components/PostCard/PostCard.tsx
src/js/components/PostCard/__snapshots__/PostCard.spec.tsx.snap
src/js/stories/Alert.stories.tsx

https://lightful.atlassian.net/browse/PLATFORM-2135
All has been reviewed by design

PLATFORM-2135: Rework alert

---

src/js/components/Button/Button.tsx
src/js/components/Button/__snapshots__/Button.spec.tsx.snap
src/js/components/Icon/Icon.spec.tsx
src/js/components/Icon/Icon.tsx
src/js/stories/Icons.stories.tsx
src/scss/custom/_icon.scss

https://lightful.atlassian.net/browse/PLATFORM-2197

PLATFORM-2197 : Rework hover state for Icons

---

src/js/components/Button/Button.tsx
src/js/components/Button/__snapshots__/Button.spec.tsx.snap
src/js/components/Icon/Icon.tsx
src/js/stories/Button.stories.tsx
src/js/stories/Icons.stories.tsx
src/js/stories/utils/themes.ts
src/scss/_buttons.scss
src/scss/_type.scss
src/scss/_variables.scss
src/scss/custom/_icon.scss

https://lightful.atlassian.net/browse/PLATFORM-2232

PLATFORM-2232: Ray 2.0 | Buttons

---

src/js/components/Button/Button.tsx
src/js/components/Button/__snapshots__/Button.spec.tsx.snap
src/js/components/Icon/Icon.tsx
src/js/stories/Button.stories.tsx
src/js/stories/Icons.stories.tsx
src/js/stories/utils/themes.ts
src/scss/_buttons.scss
src/scss/_type.scss
src/scss/_variables.scss
src/scss/custom/_icon.scss

Revert "PLATFORM-2232: Ray 2.0 | Buttons"

---

src/js/components/Button/Button.tsx
src/js/components/Button/__snapshots__/Button.spec.tsx.snap
src/js/components/Icon/Icon.tsx
src/js/stories/Button.stories.tsx
src/js/stories/Icons.stories.tsx
src/js/stories/utils/themes.ts
src/scss/_buttons.scss
src/scss/_type.scss
src/scss/_variables.scss
src/scss/custom/_icon.scss

https://lightful.atlassian.net/browse/PLATFORM-2232

PLATFORM-2232: Ray 2.0 Buttons

---

src/js/components/DropdownToggle/DropdownToggle.spec.tsx
src/js/components/DropdownToggle/DropdownToggle.tsx
src/js/components/DropdownToggle/__snapshots__/DropdownToggle.spec.tsx.snap
src/js/components/FormSelect/DropdownIndicator.tsx
src/js/stories/Dropdown.stories.tsx
src/scss/_dropdown.scss

Change the dropdown to use the primary gradient and the chevron icon, also include size props.
Again I have used the primary gradient as this matches the designs in terms of styling but not in terms of naming, We should all get on the same page with this before we make too many more changes and definitely before we release ray 2.0.
Designs for the menu can be seen here: https://www.figma.com/proto/ZgmWONpRVNrUAu5vGkG6uu/Analytics-2021?node-id=912%3A16852&scaling=min-zoom&page-id=134%3A3146&starting-point-node-id=442%3A11844
I've removed the border, added a drop shadow and reduced the padding as per the designs but I've done this using variables that we currently have so it doesn't look that much like the design. Also the border between the menu items used a grey that isn't in either …

PLATFORM-2260: Ray 2.0 | Dropdowns

---

src/js/components/PostCard/PostCard.tsx
src/js/components/PostCard/__snapshots__/PostCard.spec.tsx.snap
src/js/components/Tag/Tag.tsx
src/js/components/URLMetaPreview/URLMetaPreview.tsx
src/js/components/URLMetaPreview/__snapshots__/URLMetaPreview.spec.tsx.snap
src/scss/_variables.scss

Just changing some variables to reflect the new designs.
https://www.figma.com/file/ZtHUk0WRdban0r3wzgUm3x/Lightful-Ray-Design-System?node-id=25%3A135

PLATFORM-2264: Ray 2.0 | Typography

---

src/js/components/Progress/Progress.spec.tsx
src/js/components/Progress/Progress.tsx
src/js/components/Progress/__snapshots__/Progress.spec.tsx.snap

PLATFORM-2299 : Ray 2.0 | Progress bar

---

src/js/components/Alert/Alert.spec.tsx
src/js/components/Alert/Alert.tsx
src/js/components/Alert/__snapshots__/Alert.spec.tsx.snap
src/scss/_alert.scss

PLATFORM-2285: Ray 2.0 | Alerts

---

src/scss/_variables.scss

From Figma 
Shadow sm :
Shadow md :
Shadow lg :

PLATFORM-2286 : RAY 2.0 | Shadows

---

src/js/components/CampaignCard/CampaignCard.tsx
src/js/components/CampaignCard/__snapshots__/CampaignCard.spec.tsx.snap
src/js/components/FormSelect/Option.tsx
src/js/components/InspirationPostCard/InspirationPostCard.tsx
src/js/components/InspirationPostCard/__snapshots__/InspirationPostCard.spec.tsx.snap
src/js/components/PostCard/PostCard.tsx
src/js/components/PostCard/__snapshots__/PostCard.spec.tsx.snap
src/js/components/ResourceCard/ResourceCard.tsx
src/js/components/ResourceCard/__snapshots__/ResourceCard.spec.tsx.snap
src/js/components/SearchSuggest/SearchSuggest.tsx
src/js/components/SearchSuggest/__snapshots__/SearchSuggest.spec.tsx.snap
src/js/components/Step/Step.tsx
src/js/components/Step/__snapshots__/Step.spec.tsx.snap
src/js/components/URLMetaPreview/URLMetaPreview.tsx
src/js/components/URLMetaPreview/__snapshots__/URLMetaPreview.spec.tsx.snap
src/js/stories/Forms.stories.tsx
src/js/stories/Stepper.stories.tsx

Update some class names as per new bootstrap names. 
Update snapshot.
Update one component to functional component

Various changes

---

src/js/components/DropdownMenu/DropdownMenu.tsx
src/js/components/PostCard/PostCard.tsx
src/js/components/Progress/Progress.tsx
src/js/components/ResourceCard/ResourceCard.tsx
src/js/stories/Dropdown.stories.tsx
src/scss/_alert.scss
src/scss/_dropdown.scss
src/scss/_forms.scss
src/scss/_nav.scss
src/scss/_variables.scss
src/scss/custom/_post-card.scss
src/scss/custom/_stepper.scss
src/scss/utilities/_text.scss

PLATFORM-2326 : Design review changes

---

package.json
src/js/components/CampaignTemplateCard/CampaignTemplateCard.tsx
src/js/components/CampaignTemplateCard/__snapshots__/CampaignTemplateCard.spec.tsx.snap
src/js/components/Nav/Nav.tsx
src/js/components/PostCard/PostCard.tsx
src/js/components/PostCard/__snapshots__/PostCard.spec.tsx.snap
src/js/components/SearchInput/SearchInput.tsx
src/js/components/SearchInput/__snapshots__/SearchInput.spec.tsx.snap

Ray changes concerning https://lightful.atlassian.net/browse/PLATFORM-2356. It will be merged in a minor alpha version and reviewed by designers

PLATFORM-2356

---

README.md
package.json
src/js/components/PostCard/PostCard.tsx

Updated component to be able to have a button to add new labels in PostCard component.
On top of that, added a new yarn command to watch for changes and automatically rebuild components when using Ray as linked library in the platform. That improves development speed

PLATFORM-2303 - adding labels to posts

---

src/js/components/MediaThumbnail/MediaThumbnail.spec.tsx
src/js/components/MediaThumbnail/MediaThumbnail.tsx

I added a stretched link that goes over everything. I think it's a problem of propagation but I haven't been able to fix it and it works like that

PLATFORM-2396 : MediaThumbnails not clickable on checkbox

---

src/scss/_variables.scss

changing max-width on xl container to 1230px
PLATFORM-2361

PLATFORM-2361-container-width

---

src/scss/_variables.scss

PLATFORM-2589-instagram-heatmap-button

---

package.json
src/js/locale/i18n.tsx
yarn.lock

PLATFORM-2873-ray-language-detection (ray)

---

yarn.lock

Big dependabot pr

---

src/js/locale/uk.json

post card translation fixes

---

src/js/components/Alert/Alert.tsx
src/js/components/Alert/__snapshots__/Alert.spec.tsx.snap

Remove span wrapper for Alert children so container can be adjusted.

Remove span wrapper for Alert child

---

src/js/components/ProgressAlt/ProgressAlt.spec.tsx
src/js/components/ProgressAlt/ProgressAlt.tsx
src/js/components/ProgressAlt/__snapshots__/ProgressAlt.spec.tsx.snap
src/js/index.ts
src/js/stories/Progress.stories.tsx
src/scss/utilities/_background.scss

I went with creating a new component altogether to avoid too many conditional statement that would have made it too complicated

Add ProgressAlt

---

src/js/components/Button/Button.tsx
src/js/components/Button/__snapshots__/Button.spec.tsx.snap

Fixing small issue with block button. Removing this doesn't seem to break buttons with icons

PLATFORM-3556 : Fix buttons

---

src/scss/_variables.scss
src/scss/custom/_form-select.scss
src/scss/custom/_inspiration-post-card.scss

When updating sass on the platform it came up with some deprecation warnings that I'm addressing here

fix sass deprecation warning

---

src/js/components/Chevron/Chevron.spec.tsx
src/js/components/Chevron/Chevron.tsx
src/js/components/Chevron/__snapshots__/Chevron.spec.tsx.snap
src/js/index.ts
src/js/stories/Chevron.stories.tsx
src/scss/_custom.scss
src/scss/custom/_chevron.scss

This PR introduces a "chevron" component which is a button with the chevron icon in a chosen direction with the Ray style applied as per the figma designs
PLATFORM-3765

PLATFORM-3765 - chevron component

---

src/icons/lumiAi.svg
src/js/components/Button/Button.tsx
src/js/components/Button/__snapshots__/Button.spec.tsx.snap
src/js/components/Icon/__snapshots__/icons.spec.ts.snap
src/js/components/Icon/icons.tsx

platform pr: https://github.com/lightfulhelps/platform/pull/2612

PLATFORM-3810-larger-button-icons

---

src/js/components/Stepper/Stepper.spec.tsx
src/js/components/Stepper/Stepper.tsx
src/js/components/ToggleSwitch/ToggleSwitch.tsx
src/scss/_forms.scss

Show stepper if active step is 0.
Add primary theme for ToggleSwitch.

stepper-show

---

src/scss/_custom.scss
src/scss/custom/_row.scss

row-no-gutter
